import csv
import json
import logging
import os
import sys
import time
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import requests

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)

GITHUB_TOKEN = ""
MAX_RETRIES = 3

def get_int_env(name: str, default: int | None = None) -> int:
    val = os.getenv(name, "").strip()
    if not val:
        if default is not None:
            return default
        raise ValueError(f"Missing required environment variable: {name}")
    try:
        return int(val)
    except ValueError:
        if default is not None:
            logger.warning("Invalid value for %s: %r. Using default: %d", name, val, default)
            return default
        raise ValueError(f"Invalid integer for {name}: {val!r}")


GH_GRAPHQL = "https://api.github.com/graphql"
LABEL_ORDER = ("bug", "feature", "question", "duplicate")


def load_results(path: Path) -> list[dict]:
    if not path.exists():
        logger.error("CSV not found: %s", path)
        sys.exit(1)
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _escape(cell: str) -> str:
    """Make a string safe to drop into a Markdown table cell."""
    return (cell or "").replace("|", "&#124;").replace("\n", " ").replace("\r", " ")


def build_comment(rows: list[dict], repo: str, run_url: str) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    counts = Counter(r.get("label", "") for r in rows)
    total = len(rows)

    lines = [
        "## Daily Issue Classification Report",
        "",
        f"**Repository:** `{repo}` | **Run date:** {now} | **Total open issues:** {total}",
        "",
        "### Summary",
        "",
        "| Category | Count | Share |",
        "|----------|------:|------:|",
    ]
    for label in LABEL_ORDER:
        n = counts.get(label, 0)
        pct = f"{n / total * 100:.0f}%" if total else "-"
        lines.append(f"| **{label.capitalize()}** | {n} | {pct} |")

    lines += ["", "---", ""]

    if total == 0:
        lines += ["_No open issues to classify today._", ""]
    else:
        grouped: dict[str, list[dict]] = {lbl: [] for lbl in LABEL_ORDER}
        for r in rows:
            grouped.setdefault(r.get("label", "question"), grouped["question"]).append(r)

        for label in LABEL_ORDER:
            group = grouped[label]
            if not group:
                continue
            lines += [
                f"### {label.capitalize()}s ({len(group)})",
                "",
                "| # | Title | Reason |",
                "|---|-------|--------|",
            ]
            for r in group:
                num = r.get("number", "?")
                title = _escape(r.get("title", ""))[:60]
                reason = _escape(r.get("reason", ""))[:120]
                url = f"https://github.com/{repo}/issues/{num}"
                lines.append(f"| [#{num}]({url}) | {title} | {reason} |")
            lines.append("")

    footer = (
        f"<sub>Generated by the [Daily Issue Classifier]({run_url}) workflow</sub>"
        if run_url
        else "<sub>Generated by the Daily Issue Classifier workflow</sub>"
    )
    lines += ["---", "", footer]
    return "\n".join(lines)


def graphql(query: str, variables: dict) -> dict:
    """Call the GitHub GraphQL API with retry on transient errors."""
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Content-Type": "application/json",
    }
    last_exc: Exception | None = None
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = requests.post(
                GH_GRAPHQL,
                headers=headers,
                json={"query": query, "variables": variables},
                timeout=30,
            )
            # Only retry on 5xx or transient connection errors.
            # 4xx errors are usually client-side and shouldn't be retried.
            if 400 <= resp.status_code < 500:
                resp.raise_for_status()

            if resp.status_code >= 500:
                raise requests.HTTPError(f"Server error {resp.status_code}")

            resp.raise_for_status()
            payload = resp.json()
            if "errors" in payload:
                # Do not retry on GraphQL logic errors (e.g. missing discussion)
                raise ValueError(f"GraphQL errors: {json.dumps(payload['errors'])}")

            return payload["data"]
        except (requests.HTTPError, ValueError) as exc:
            # Fatal error, do not retry
            raise exc
        except (requests.RequestException) as exc:
            # Transient network error, retry
            last_exc = exc
            wait = min(2 ** attempt, 15)
            logger.warning(
                "GraphQL call failed (attempt %d/%d): %s; retrying in %ds",
                attempt, MAX_RETRIES, exc, wait,
            )
            time.sleep(wait)
    raise RuntimeError(f"GraphQL call failed after {MAX_RETRIES} retries: {last_exc}")


GET_DISCUSSION_ID = """
query($owner: String!, $name: String!, $number: Int!) {
  repository(owner: $owner, name: $name) {
    discussion(number: $number) { id }
  }
}
"""

ADD_COMMENT = """
mutation($discussionId: ID!, $body: String!) {
  addDiscussionComment(input: {discussionId: $discussionId, body: $body}) {
    comment { id url }
  }
}
"""


def main() -> None:
    # Read environment variables inside main to avoid top-level crashes
    token = os.getenv("GITHUB_TOKEN", "").strip()
    repo = os.getenv("GITHUB_REPO", "").strip()
    if not token or not repo:
        missing = [n for n, v in [("GITHUB_TOKEN", token), ("GITHUB_REPO", repo)] if not v]
        raise ValueError(f"Missing required environment variables: {', '.join(missing)}")

    if "/" not in repo:
        raise ValueError(f"GITHUB_REPO must be 'owner/name', got: {repo!r}")
    owner, name = repo.split("/", 1)

    # Use globals or pass these as arguments to functions.
    # For simplicity, we'll keep them as local variables and update the global-like usage if needed,
    # but the graphql() function uses GITHUB_TOKEN from the global scope currently.
    global GITHUB_TOKEN, MAX_RETRIES
    GITHUB_TOKEN = token
    MAX_RETRIES = get_int_env("MAX_RETRIES", 3)

    discussion_number = get_int_env("DISCUSSION_NUMBER")
    run_url = os.getenv("RUN_URL", "")
    dry_run = os.getenv("DRY_RUN", "false").lower() == "true"
    csv_path = Path(os.getenv("CSV_PATH", "classified_issues.csv"))

    rows = load_results(csv_path)
    body = build_comment(rows, repo, run_url)

    if dry_run:
        print(body)
        logger.info("Dry run complete; no comment posted.")
        return

    data = graphql(GET_DISCUSSION_ID, {"owner": owner, "name": name, "number": discussion_number})
    disc = data.get("repository", {}).get("discussion") if data else None
    if not disc:
        raise RuntimeError(f"Discussion #{discussion_number} not found in {repo}.")

    result = graphql(ADD_COMMENT, {"discussionId": disc["id"], "body": body})
    url = result["addDiscussionComment"]["comment"]["url"]
    logger.info("Comment posted: %s", url)
    print(f"Summary posted: {url}")


if __name__ == "__main__":
    main()
