import csv, json, logging, os, sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

GITHUB_TOKEN      = os.environ["GITHUB_TOKEN"]
GITHUB_REPO       = os.environ["GITHUB_REPO"]
DISCUSSION_NUMBER = int(os.environ["DISCUSSION_NUMBER"])
RUN_URL           = os.getenv("RUN_URL", "")
DRY_RUN           = os.getenv("DRY_RUN", "false").lower() == "true"
CSV_PATH          = Path("classified_issues.csv")
GH_GRAPHQL        = "https://api.github.com/graphql"
LABEL_EMOJI       = {"bug": "Bug", "feature": "Feature", "question": "Question", "duplicate": "Duplicate"}

def load_results(path):
    if not path.exists():
        logger.error("CSV not found: %s", path); sys.exit(1)
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def build_comment(rows, repo, run_url):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    counts = Counter(r["label"] for r in rows)
    total  = len(rows)
    lines  = [
        "## Daily Issue Classification Report",
        "",
        f"**Repository:** `{repo}`  |  **Run date:** {now}  |  **Total open issues:** {total}",
        "",
        "### Summary",
        "",
        "| Category | Count | Share |",
        "|----------|------:|------:|",
    ]
    for label in ("bug", "feature", "question", "duplicate"):
        n = counts.get(label, 0)
        pct = f"{n / total * 100:.0f}%" if total else "-"
        lines.append(f"| **{label.capitalize()}** | {n} | {pct} |")
    lines += ["", "---", ""]
    grouped = {"bug": [], "feature": [], "question": [], "duplicate": []}
    for r in rows: grouped.get(r["label"], grouped["question"]).append(r)
    for label in ("bug", "feature", "question", "duplicate"):
        group = grouped[label]
        if not group: continue
        lines += [f"### {label.capitalize()}s ({len(group)})", "", "| # | Title | Reason |", "|---|-------|--------|"]
        for r in group:
            num = r["number"]; title = r["title"][:60].replace("|","&#124;")
            reason = r.get("reason","").replace("|","&#124;")[:120]
            url = f"https://github.com/{repo}/issues/{num}"
            lines.append(f"| [#{num}]({url}) | {title} | {reason} |")
        lines.append("")
    lines += ["---", "", f"<sub>Generated by the [Daily Issue Classifier]({run_url}) workflow</sub>"]
    return "\n".join(lines)

def graphql(query, variables):
    headers = {"Authorization": f"Bearer {GITHUB_TOKEN}", "Content-Type": "application/json"}
    resp = requests.post(GH_GRAPHQL, headers=headers, json={"query": query, "variables": variables}, timeout=30)
    resp.raise_for_status()
    payload = resp.json()
    if "errors" in payload: raise RuntimeError(f"GraphQL errors: {json.dumps(payload['errors'])}")
    return payload["data"]

GET_DISCUSSION_ID = """
query($owner: String!, $name: String!, $number: Int!) {
  repository(owner: $owner, name: $name) {
    discussion(number: $number) { id }
  }
}"""

ADD_COMMENT = """
mutation($discussionId: ID!, $body: String!) {
  addDiscussionComment(input: {discussionId: $discussionId, body: $body}) {
    comment { id url }
  }
}"""

def main():
    owner, name = GITHUB_REPO.split("/", 1)
    rows = load_results(CSV_PATH)
    if not rows: sys.exit(0)
    body = build_comment(rows, GITHUB_REPO, RUN_URL)
    if DRY_RUN:
        print(body); logger.info("Dry run complete."); return
    data = graphql(GET_DISCUSSION_ID, {"owner": owner, "name": name, "number": DISCUSSION_NUMBER})
    disc = data.get("repository", {}).get("discussion")
    if not disc: raise RuntimeError(f"Discussion #{DISCUSSION_NUMBER} not found.")
    result = graphql(ADD_COMMENT, {"discussionId": disc["id"], "body": body})
    url = result["addDiscussionComment"]["comment"]["url"]
    logger.info("Comment posted: %s", url)
    print(f"Summary posted: {url}")

if __name__ == "__main__":
    main()
